model:
  class: ResNet
  conv1:
    in_channels: 3
    out_channels: 16
    kernel_size: 1
    stride: 1
  block_groups:
    - n: 3
      in_channels: 16
      out_channels: 16
      stride: 1
      shortcut: "pad"
    - n: 3
      in_channels: 16
      out_channels: 32
      stride: 2
      shortcut: "pad"
    - n: 3
      in_channels: 32
      out_channels: 64
      stride: 2
      shortcut: "pad"
  linear:
    in_features: 64
    out_features: 10
hyperparams:
  lr: 1e-2